# Acessando Dimensões no Array

In [1]:
import pandas as pd
import numpy as np

In [6]:
#Gerando um array aleatorio de 10 linhas e 2 colunas
#Formato linha,coluna
my_array = np.random.randint(1,20, size=(10,2))

In [7]:
my_array

array([[ 1, 17],
       [19, 16],
       [13,  9],
       [ 9,  4],
       [ 9, 14],
       [17, 11],
       [ 1, 10],
       [18,  4],
       [ 9, 17],
       [11, 10]])

In [15]:
#Imprimindo a 1 linha
my_array[0]

array([ 1, 17])

In [19]:
#Imprimindo a o 1º elemento da linha 4
my_array[3][0]

9

In [21]:
#Imprimindo até 3 valores da coluna 1
my_array[:3,0]

array([ 1, 19, 13])

In [22]:
#Outra forma de acessar os valores
my_array[3,0]

9

In [26]:
#Imprimindo todos os valores da coluna 1 e multiplicando por 2
my_array[:,1] * 2

array([17, 16,  9,  4, 14, 11, 10,  4, 17, 10])

In [32]:
my_array

array([[ 1, 17],
       [19, 16],
       [13,  9],
       [ 9,  4],
       [ 9, 14],
       [17, 11],
       [ 1, 10],
       [18,  4],
       [ 9, 17],
       [11, 10]])

In [31]:
#Comparando elementos do array
my_array > 10
#NOTA!: Desse metodo só retorna o booleano

array([[False,  True],
       [ True,  True],
       [ True, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [False, False],
       [ True, False],
       [False,  True],
       [ True, False]])

In [33]:
#Retornando os valores inteiros
my_array[my_array>10]

array([17, 19, 16, 13, 14, 17, 11, 18, 17, 11])

# Carregando Arrays NumPy a partir de arquivos de Texto

In [38]:
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [40]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [3]:
random_data = np.random.randint(1,10, size=(5,3))

In [4]:
my_array2 = np.array(random_data)

In [4]:
my_array2.dtype = [('A','i4'),('B','i4'),('C','i4')]

In [6]:
my_array2

array([[(6, 8, 7)],
       [(8, 9, 8)],
       [(3, 1, 2)],
       [(9, 4, 8)],
       [(9, 5, 4)]], dtype=[('A', '<i4'), ('B', '<i4'), ('C', '<i4')])

In [9]:



my_array2['A']

array([[6],
       [8],
       [3],
       [9],
       [9]])

In [14]:
fmt = ['%s']  # Use '%s' para strings, '%d' para inteiros



In [15]:
np.savetxt("dataset_valores.txt",my_array2,delimiter=',',fmt = fmt)

In [16]:
my_array2['C']

array([[7],
       [8],
       [2],
       [8],
       [4]])

In [17]:
my_array2

array([[(6, 8, 7)],
       [(8, 9, 8)],
       [(3, 1, 2)],
       [(9, 4, 8)],
       [(9, 5, 4)]], dtype=[('A', '<i4'), ('B', '<i4'), ('C', '<i4')])

In [5]:
np.savetxt("dataset_valores.txt",my_array2,delimiter=',')