# Numpy Arrays Vs Listas
 - Arrays Numpy permietem fazermos operações em __arrays inteiros__ de forma rápida.
 - Listas não permitem operações em todos os elementos da lista
 - Para operações em todos os elementos é preciso interar sobre toda a lista
 - Listas em Python armazenam diferentes tipos de objetos
 - Arrays Numpy considera todos os elementos de tipos distintos como strings

In [1]:
#Criando uma lista em python
lista = [1,2,3]

In [2]:
lista

[1, 2, 3]

In [4]:
#Multiplica valores da lista por 2
lista * 2

[1, 2, 3, 1, 2, 3]

In [6]:
# Transforme a variavel lista em um array Numpy
import numpy as np


lista = np.array(lista)

In [7]:
type(lista)

numpy.ndarray

Apos feita a transformação da lista em um __Array Numpy__ a lista ira se comportar de outra forma fazendo com que cada elemento seja multiplicado por 2

In [8]:
lista * 2

array([2, 4, 6])

In [9]:
# Calculando IMC de pessoas
pesos = [67,83,54]
altura = [1.67,1.83,1.54]


In [10]:
pesos / altura ** 2
#Sem a transformação dos valores em arrays numpy gera um erro
#As possiveis soluções seria criar laços iterando elemento por elemento para ser feito o calculo acima

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [11]:
#transformando o exemplo anterior em arrays numpy  
pesos = np.array(pesos)
altura = np.array(altura)

In [12]:
pesos / altura ** 2

array([24.02380867, 24.78425752, 22.76943835])

In [13]:
imc = pesos / altura ** 2

In [15]:
imc[0]

24.023808670084982

In [16]:
#NOTA!: Arrays armazena elementos como string quando este não são inteiros ou float
a = np.array([1,3,'casa',True])

In [17]:
a

array(['1', '3', 'casa', 'True'], dtype='<U11')

In [18]:
a *2
#As listas do array numpy são menos flexiveis considerando todos os dados homogeneos

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [1]:
#Adicionando elementos a um array
import pandas as pd
import numpy as np

In [3]:
lista = [[1,2,3],[4,5,6]]

In [7]:
lista = np.array(lista)

In [5]:
lista = np.insert(lista,0,10)

In [6]:
lista 

array([10,  1,  2,  3,  4,  5,  6])

In [8]:
#deletando um elemento do array
lista = np.delete(lista,[0])
lista

array([1, 2, 3, 4, 5, 6])

In [9]:
# Gerando um arquivo.txt apartir de um array
np.savetxt("dataset_array.txt", lista,delimiter=',')