# Utils


In [1]:
import numpy as np

In [23]:
# Métodos disponiveis (digite o . pressione tab).
lista = [[1,2,3],[4,5,6]]

In [24]:
lista = np.array(lista)

In [25]:
lista * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
#Retorna a forma do array no formato de linhas e colunas
lista.shape

(2, 3)

In [27]:
#Retorna a quantidade de dimensões
lista.ndim

2

In [28]:
#Imprime o valor maximo do array
lista.max()

6

In [29]:
#Imprime o valor minimo do array
lista.min()

1

In [30]:
lista.mean()
#NOTA!: achava que retornaria a media entre o menor valor(1) e o maior valor (6) que seria 3
#NOTA!: Na lista [[1, 2, 3], [4, 5, 6]], a soma total dos elementos é 21. Dividindo por 6 (quantidade total de elementos), obtemos 3.5

3.5

In [32]:
# Imprime o desvio padrão
lista.std()

1.707825127659933

In [34]:
#imprimindo o tipo de dado
lista.dtype

dtype('int32')

In [35]:
#Imprime a quantidade de elementos
lista.size

6

In [40]:
#Imrprime a quantidade em bytes dos itens
lista.itemsize

4

In [41]:
#Somando todos os elementos do array()
lista.sum()

21

# Transformando Arrays

In [42]:
lista

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
#Gera a Transposta da Matris (linha -> coluna)
lista.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
#Transformando uma matriz em um vetor (linha)
lista.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [50]:
#Gerando numeros aleatorios de 1 a 20 e colocando em uma matriz 5 por 3(5 linhas x 3 colunas)
lin5_col3 = np.random.randint(1,21, size=(5,3))

In [51]:
lin5_col3

array([[10,  2,  6],
       [10, 17,  3],
       [ 7, 18,  4],
       [ 4, 18, 16],
       [13, 10, 19]])

In [52]:
lin5_col3.shape

(5, 3)

In [53]:
#Transformando a em uma matriz com 3 linhas e 5 colunas
lin5_col3.reshape(3,5)

array([[10,  2,  6, 10, 17],
       [ 3,  7, 18,  4,  4],
       [18, 16, 13, 10, 19]])

In [60]:
lin5_col3.reshape(-1)#NOTA!: Estão todos na mesma linha

array([10,  2,  6, 10, 17,  3,  7, 18,  4,  4, 18, 16, 13, 10, 19])

In [58]:
col = lin5_col3.reshape(1,15)
col#NOTA!: Cada numero agora representa uma coluna

array([[10,  2,  6, 10, 17,  3,  7, 18,  4,  4, 18, 16, 13, 10, 19]])